# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa508d5892c98d046420126dfa91075270d321bee0c883ed4f755ba2c71f2339d95efa97380faded46326f84df596f4b7c1e962ee13ab91e09eeabdde2bded06

test:
  secret_key_base: 41e32bc558078e394d5655ee717748013262c877d92e40709c61ac9496a88ce934871616c18b01ac615095a64ee2546bd5acb9f47f11ee606516735acc3dea2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
